### ISSUE TITLE
Failure in BOOTSTRAPATTR upon dumping an AST

### ISSUE THREAD

**Issue by drforr** [tony-o/perl6-data-dump#1]
--cut here--
use Data::Dump;
say Dump($p.parsefile( $filename ).ast);
--cut here--

The data structure I'm trying to dump:
--cut here--
ANTLR4::Actions::Perl6::Shim.new(ast => {:actions([]), :content([{:action(Any), :attribute([]), :content([{:content([{:commands([]), :content([{:!complemented, :content("INT"), :!greedy, :modifier(Any), :type("nonterminal")}]), :label(Any), :options([]), :type("concatenation")}, {:commands([]), :content([{:!complemented, :content([{:content([{:!complemented, :content("INT"), :!greedy, :modifier("?"), :type("nonterminal")}, {:!complemented, :content("_"), :!greedy, :modifier(Any), :type("terminal")}, {:!complemented, :content("INT"), :!greedy, :modifier("?"), :type("nonterminal")}]), :type("alternation")}]), :!greedy, :modifier(Any), :type("capturing group")}]), :label(Any), :options([]), :type("concatenation")}]), :type("alternation")}]), :locals(Any), :name("repeat"), :options([]), :returns(Any), :throws([])}]), :import([]), :name("Abnf"), :options([]), :tokens([]), :type(Any)}<>, perl6 => "grammar Abnf { rule repeat { ( ( <INT> )=2= ( ( ( <INT>? '_' <INT>? )=1= )=3= )=2= )=1= } }")
--cut here--

perl6 -I../../External-Repositories/json/lib -Ilib examples/antlr2perl6 Abnf.g4 > Abnf.pm
Method 'Str' not found for invocant of class 'BOOTSTRAPATTR'
  in block  at lib/Data/Dump.pm6:59
  in sub Dump at lib/Data/Dump.pm6:53
  in block  at lib/Data/Dump.pm6:40
  in sub Dump at lib/Data/Dump.pm6:33
  in sub Dump at lib/Data/Dump.pm6:46
  in block  at lib/Data/Dump.pm6:40
  in sub Dump at lib/Data/Dump.pm6:33
  in sub Dump at lib/Data/Dump.pm6:46
  in block  at lib/Data/Dump.pm6:40
  in sub Dump at lib/Data/Dump.pm6:33
  in sub Dump at lib/Data/Dump.pm6:46
  in block  at lib/Data/Dump.pm6:40
  in sub Dump at lib/Data/Dump.pm6:33
  in sub Dump at lib/Data/Dump.pm6:46
  in block  at lib/Data/Dump.pm6:40
  in sub Dump at lib/Data/Dump.pm6:33
  in sub MAIN at examples/antlr2perl6:9
  in block <unit> at examples/antlr2perl6:4

**Comment by tony-o** [comment]
@drforr can you give it a shot with the version i just uploaded?  it shouldn't die now but it may not show everything you're looking for.

**Comment by tony-o** [comment]
issue resolved and output looks good - closing per our irc discussion.

``` irc
09:53 < tony-o_> DrForr: was that more along the lines of what you were looking for?
09:54 < tony-o_> i added a controllable recursion depth because i let it sit for 5 minutes with no output during one
                 of the tests
09:54 < DrForr> I just got home, haven't looked at anything yet.
09:58 < DrForr> Yes, excellent.
09:59 < tony-o_> cool, i'll close the bug out on github.  thanks for creating the issue
```
