### ISSUE TITLE
No color following rakudo upgrade

### ISSUE THREAD

**Issue by selkovjr** [tony-o/perl6-data-dump#27]
I have upgraded rakudobrew and my current perl version is:

    2017.04.3-162-g701dab3 built on MoarVM version 2017.04-44-gf0db882

The upgrade failed initially, so I had to nuke the previous installation, installing all packages from scratch:

```
panda list | ack 'ANSI|Dump' | ack installed
Data::Dump                                    [installed]
Terminal::ANSIColor                           [installed]
```
```
echo $TERM
xterm-256color
```

New packages passed all tests, but Dump does not output ANSI color codes. Is there a method for finding out where it fails?

**Comment by zoffixznet** [comment]
Fixed by https://github.com/tony-o/perl6-data-dump/pull/29
