### ISSUE TITLE
Feature Request: Add option to omit data types

### ISSUE THREAD

**Issue by 0racle** [tony-o/perl6-data-dump#33]
When working with nested data, I sometimes just want a pretty indented output of the structure.

I find in these cases, the postfix type annotation (eg. `34.Int`, `"this".Str`) clutters the output. Sometimes I resort to converting to JSON instead, but that also introduces some other clutter.

I would appreciate another option that omits the postfix type annotation.

P.S. Thanks for this module.

**Comment by tony-o** [comment]
@0racle this should be doable now with `:no-postfix`.  Also added a feature I've been working on to override how certain data types are dumped (see `:overrides`). 

Check it out and lmk if that does it for this FR.

**Comment by 0racle** [comment]
Nice! Thanks for the prompt response. Overrides looks useful too.
