### ISSUE TITLE
Wishlist: Option to dump without colour

### ISSUE THREAD

**Issue by zoffixznet** [tony-o/perl6-data-dump#5]
I have Term::ANSIColor installed for other purposes, but that causes Data::Dump to print in colour.

It uses a very dark shade of red for keys of hashes that I can barely see on my screen. I really wish there was a way to either change their colours or remove colour completely.

**Comment by tony-o** [comment]
@zoffixznet i'll add this in tonight

**Comment by tony-o** [comment]
@zoffixznet does passing the option `:color(False)` to `Dump(...)` not work?

**Comment by zoffixznet** [comment]
> does passing the option :color(False) to Dump(...) not work?

It works! Thanks. `:!color` works too. Would be nice for that to be documented.

**Comment by tony-o** [comment]
docs updated to reflect the option and PR #9 merged - please close if it's all good

**Comment by zoffixznet** [comment]
Perfect! Thanks a lot.
